### ISSUE TITLE
Fix compatilbility with recent Dancer2 versions

### ISSUE THREAD

**Issue by abeverley** [markov2/perl5-Log-Report#12]
A very simple fix, could you please add `return` before the `send_as` call here? https://github.com/markov2/perl5-Log-Report/blob/8f9a4175ccf28c2e5caa332a287d17efc003958b/lib/Dancer2/Plugin/LogReport.pm#L400

i.e. `return $dsl->send_as(plain => "$msg")`

I've just opened [a new issue on Dancer2](https://github.com/PerlDancer/Dancer2/issues/1712), and this plugin has the same problem, in that in [this commit](https://github.com/PerlDancer/Dancer2/commit/3331ad7062e1264a87c0fbb7c47ba6ea3e06accd) it is now possible that `send_as` will not necessarily jump out of its current location.

**Comment by markov2** [comment]
I really hate Dancer2's breaks in control flow.

Released as version 1.37

**Comment by abeverley** [comment]
> I really hate Dancer2's breaks in control flow.

You and me both :)

> Released as version 1.37

Thanks!
