### ISSUE TITLE
Version check failing against latest Dancer2 version

### ISSUE THREAD

**Issue by abeverley** [markov2/perl5-Log-Report#14]
This is being produced when using `Dancer2::Plugin::LogReport.pm` with the latest Dancer2 version:
```
Argument "1.1.1" isn't numeric in numeric gt (>) at /usr/share/perl5/Dancer2/Plugin/LogReport.pm line 35.
```
Functionality does not seem to be affected, as it's still using the correct `$level`. I'm not sure of the best way to do the version check instead?

**Comment by markov2** [comment]
This should have been fixed by https://github.com/markov2/perl5-Log-Report/commit/210aa76fb7aeaa262484c02516f610b4f5c2ad57 (Tom Hukins) for release 1.35 (Oct 2023)

**Comment by abeverley** [comment]
Sorry, my mistake. I thought I was running the latest version but apparently not. I can confirm already fixed :)
